type AnalysisResult = {
  isScopeCreep: boolean;
  riskLevel: "LOW" | "MEDIUM" | "HIGH";
  violatedClause: string;
  analysis: string;
  estimatedExtraHours: number;
  suggestedEmailResponse: string;
};

const RISK_COLORS: Record<AnalysisResult["riskLevel"], [number, number, number]> = {
  HIGH: [185, 79, 67],
  MEDIUM: [213, 139, 49],
  LOW: [13, 118, 110],
};

export async function downloadAnalysisPdf(result: AnalysisResult, clientRequest: string) {
  // Dynamic import keeps jsPDF out of the server bundle (client-side only).
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = 0;

  const ensureSpace = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = 56;
    }
  };

  const writeWrapped = (text: string, size: number, color: [number, number, number], gapAfter = 8, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxWidth) as string[];
    for (const line of lines) {
      ensureSpace(size + 6);
      doc.text(line, margin, y);
      y += size + 4;
    }
    y += gapAfter;
  };

  const sectionTitle = (title: string) => {
    ensureSpace(30);
    writeWrapped(title.toUpperCase(), 9, [94, 104, 110], 4, true);
  };

  // Header band
  doc.setFillColor(16, 24, 32);
  doc.rect(0, 0, pageWidth, 96, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(244, 241, 234);
  doc.text("ScopeGuard AI", margin, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(150, 155, 156);
  doc.text("Scope Change Assessment", margin, 60);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, 76);

  y = 124;

  // Verdict line
  const verdict = result.isScopeCreep ? "EXTRA WORK" : "WITHIN SCOPE";
  const verdictColor: [number, number, number] = result.isScopeCreep ? [185, 79, 67] : [13, 118, 110];
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(verdictColor[0], verdictColor[1], verdictColor[2]);
  doc.text(`Assessment: ${verdict}`, margin, y);
  y += 22;

  const riskColor = RISK_COLORS[result.riskLevel];
  doc.setFontSize(11);
  doc.setTextColor(16, 24, 32);
  doc.text(`Risk level: ${result.riskLevel}`, margin, y);
  y += 18;
  doc.text(`Estimated additional hours: ${result.estimatedExtraHours}`, margin, y);
  y += 26;

  sectionTitle("Client request");
  writeWrapped(clientRequest || "(none provided)", 10, [16, 24, 32]);

  sectionTitle("Relevant clause");
  writeWrapped(result.violatedClause, 10, [16, 24, 32]);

  sectionTitle("Analysis");
  writeWrapped(result.analysis, 10, [16, 24, 32]);

  sectionTitle("Suggested response");
  writeWrapped(result.suggestedEmailResponse, 10, [16, 24, 32]);

  // Footer on every page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 155, 156);
    doc.text(
      `Generated by ScopeGuard AI · Page ${i} of ${pages}`,
      margin,
      doc.internal.pageSize.getHeight() - 28
    );
  }

  // Risk color accent bar on first page edge
  doc.setPage(1);
  doc.setFillColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.rect(0, 96, pageWidth, 4, "F");

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  doc.save(`Scope_Assessment_${timestamp}.pdf`);
}
